name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to S3
        uses: aws-actions/s3-sync@latest
        with:
          aws-access-key-id: ${{ secrets.DIVER_S3_ACCESS_USER_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DIVER_S3_ACCESS_USER_ACCESS_KEY }}
          bucket: diver-web-app-test
          source: .
          acl: public-read
          github-token: ${{ secrets.GITHUB_TOKEN }}
